### ISSUE TITLE
1.2.0 installer and windows 8.1

### ISSUE THREAD

**Issue by boriscallens** [SiliconStudio/paradox#252] opened 2015-07-20 08:11 UTC
Immediately after launching paradox.exe a message saying 'An instance of Paradox Launcher is already running' pops up. Taskmanager shows no such instance.
When I run the same exe with the compatibility troubleshooter it suggests 'Windows 8 mode' and now the installer works.

Before I found the solution I tried the following things without luck

   - reboot, run
   - uninstall, reboot, install, run
   - run as admin

I run windows 8.1 enterprise x64 (everything patched to latest).

**Comment by xen2** [comment] 2015-07-23 09:01
Can you give another try with latest launcher without Windows 8 mode please?

**Comment by boriscallens** [comment] 2015-07-23 19:32
I opened the installer (with compatibilty mode enabled) and an auto-update happened.
The bottom right corner now says v1.2.1. Closed launcher and tried launching.

When disabled the message 'An instance of Paradox Launcher is already running' pops up.
When re-enabled everything runs fine ...
No suspicious activity in the process explorer, no relevant event-viewer entries.
Anything else I can check for you?

**Comment by xen2** [comment] 2015-07-24 02:59
If you run the app through Standard User Analyzer tool with "elevated" unchecked, (download: http://www.microsoft.com/en-us/download/details.aspx?id=7352 ), does Anything suspicious in the log?

Thanks for offering your help resolving this issue! (esp. since we can't reproduce it)

**Comment by xen2** [comment] 2015-07-24 03:01
Also, you run Windows Enterprise. Did you join a domain? Could it be overriding some security rules?

**Comment by boriscallens** [comment] 2015-07-24 07:26
Not at home now, so can't check immediately.
I can say that I don't run a domain and that I haven't done anything specific with security rules.

(we get an msdn subscription from work, hence enterprise at home)

**Comment by boriscallens** [comment] 2015-07-24 15:03
When I run it without any compatibility checks enabled through the SUA, everything works perfectly without a single warning or error.
When I run it manually, I still need the compatibility check enabled.

As this appears to be on my machine only, I have a workaround and I can't give you more information I suggest you close this issue as 'cant reproduce' and move on?
If you want to put more effort into this I could maybe arrange a desktop sharing (teamviewer?) session. I'm in Belgium (gmt+2 currently).

**Comment by najak3d** [comment] 2015-08-03 01:21
I last tried Paradox February of this year.  Just came back today to check the progress... and after installing the latest .exe today, I get this same error, and so I can't regenerate any of the sample projects.  Is there a workaround?   Right now, I am unable to use it.

**Comment by xen2** [comment] 2015-08-03 05:19
@boriscallens mentionned a fix
> When I run the same exe with the compatibility troubleshooter it suggests 'Windows 8 mode' and now the installer works.

Does it fix it for your situation or not?

**Comment by najak3d** [comment] 2015-08-03 06:10
Sorry, that's not an option.  I should have also said that I'm on Windows 7.  The release in February ran just fine on Win7.  My PC is only a year old, but I ordered one with win7 to avoid Win8.

**Comment by xen2** [comment] 2015-08-03 06:16
> Sorry, that's not an option. I should have also said that I'm on Windows 7. The release in February ran just fine on Win7. My PC is only a year old, but I ordered one with win7 to avoid Win8.

Sorry, since the title of the issue was Win8, I assumed that's what you had.
What exact Win7 version do you have? Enterprise?

**Comment by najak3d** [comment] 2015-08-03 15:56
Win7 Home Premium here, running on a Dell XPS.  Thanks for your time.

**Comment by xen2** [comment] 2015-08-07 08:13
@boriscallens @najak3d 
Could you please try with newest launcher (1.3.0)? If you can't upgrade due to this failure, just download installer from Paradox website.

**Comment by boriscallens** [comment] 2015-08-07 14:53
After starting the launcher, I got a popup saying it was upgrading.
During the download I disabled the compatibility settings.
Now when pressing the start button in the launcher it works :+1: 

It does still say Version 1.2 in the launcher though, but I'm guessing that's a different story.

**Comment by najak3d** [comment] 2015-08-07 17:05
Xen2, thanks for your response.  I'm not seeing how to "try with newest launcher".  The main website still show 1.2.  So how do I combine the 1.2 release with the 1.3.0 launcher?

**Comment by jmkinzer** [comment] 2015-08-07 17:11
The launcher and paradox version are unrelated. This may help answer your question:
http://answers.paradox3d.net/questions/1526/version-121-has-been-released.html

**Comment by najak3d** [comment] 2015-08-07 19:14
When I go to the main site to download, it still just shows the July 16th release, so I assume it hasn't changed since I last downloaded it.   I'm patient, not in a hurry here (am working on the game logic using crude 2D rendering in XNA for now), so I'll just wait for the next full release, and assume that the fix will be included with it.  Let me know if for some reason this plan sounds flawed.  

Paradox is currently the leading contender for game engine that we will use for the final product.  In February, when I first tried it out, Paradox was the only engine that "just worked" for Windows as well as for Android, first try.  I was very impressed, and I expect to see many more good things come from this engine.

On a side note -- is Edit-and-Continue still disabled due to the use of the portable libraries, or has MS fixed this for us yet?  I'm hoping that'll be fixed within the next 6 months, if not fixed already.

**Comment by xen2** [comment] 2015-08-11 05:26
@najak3d Where did you see July 16th release? ParadoxSetup.exe is updated separately (it packages the latest launcher, which is versioned independently from Paradox).

I think new setup/launcher posted on website should work good for everybody now.
Please reopen if you still have issues related to this.

**Closed by xen2** 2015-08-11 05:26 UTC
Labels: bug, fixed
