### ISSUE TITLE
Light Culling corrupting game / scene renderer.

### ISSUE THREAD

**Issue by HugoPeters** [SiliconStudio/paradox#213] opened 2015-05-04 16:40 UTC
I'm trying to render 1 set of objects using a certain lighting configuration, and anther set without any light influence. I'm trying to accomplish this with this render pipeline:

![](http://i.imgur.com/gDwQv7c.png)

The last Render Camera uses the same camera as the first, but it only renders 1 group of objects. The first doesn't render this group.

Now, when I set the culling masks of lights to the separate groups, Paradox totally flips.

![](http://i.imgur.com/UWYxYoS.png)

![](http://i.imgur.com/VeNxkqI.png)

![](http://i.imgur.com/bVQxjmA.png)
(there used to be 2 cubes...)

![](http://i.imgur.com/1m59oa5.png)

Here's a download to an example solution I quickly made up which demonstrates the crash
https://mega.co.nz/#!Wl02BIJY!UN5vlEYMJpf1PKRRDmhdwz3qNiaIBZ34Fs44i8OI8Tc

**Comment by jwollen** [comment] 2015-05-28 05:50
Thanks for reporting. The exception (and disappearance of models) has been fixed on our development branch and will be integrated in the next release.

I can't reproduce image 2 and 3 though. Can you provide more detail on how these happened?

**Closed** 2015-06-12 00:45 UTC
Labels: bug, fixed
