### ISSUE TITLE
Engine startup fail

### ISSUE THREAD

**Issue by astearon** [SiliconStudio/paradox#304] opened 2015-09-12 22:45 UTC
Paradox Version: 1.2.2-beta
GameStudio Version: 4
Current Directory: C:\Program Files\Silicon Studio\Paradox
Command Line Args: 
OS Version: Microsoft Windows NT 6.2.9200.0 (x86)
Processor Count: 4
Video configuration:
GPU 1
BitsPerPel: 32
Caption: Intel(R) HD Graphics
Description: Intel(R) HD Graphics
DeviceName: Intel(R) HD Graphics
DisplayFlags: 0
DisplayFrequency: 60
DitherType: 
DriverVersion: 
ICMIntent: 
ICMMethod: 
LogPixels: 96
PelsHeight: 768
PelsWidth: 1024
SettingID: Intel(R) HD Graphics
SpecificationVersion: 1025
Exception: InvalidOperationException: Error while loading default package from [C:/Program Files/Silicon Studio/Paradox/GamePackages/Paradox.1.2.2-beta\Paradox.pdxpkg]: []: Error: Error while pre-loading package [C:\Program Files\Silicon Studio\Paradox\GamePackages\Paradox.1.2.2-beta\Paradox.pdxpkg]. System.BadImageFormatException: Could not load file or assembly 'SiliconStudio.Paradox.Importer.Assimp, Version=1.0.5701.32808, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'SiliconStudio.Paradox.Importer.Assimp, Version=1.0.5701.32808, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.RuntimeType.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
   at SharpYaml.Serialization.AttributeRegistry.GetAttributes(MemberInfo memberInfo, Boolean inherit)
   at SiliconStudio.Core.Yaml.YamlSerializer.AtributeRegistryFilter.GetAttributes(MemberInfo memberInfo, Boolean inherit)
   at SharpYaml.Serialization.AssemblyRegistry.RegisterAssembly(Assembly assembly, IAttributeRegistry attributeRegistry)
   at SharpYaml.Serialization.SerializerSettings.RegisterAssembly(Assembly assembly)
   at SiliconStudio.Core.Yaml.YamlSerializer.CreateSerializer(Boolean keepOnlySealedOverrides, Serializer& localSerializer)
   at SiliconStudio.Core.Yaml.YamlSerializer.GetYamlSerializer(Boolean keepOnlySealedOverrides)
   at SiliconStudio.Core.Yaml.YamlSerializer.Deserialize(Stream stream, Type expectedType, SerializerContextSettings contextSettings)
   at SiliconStudio.Assets.Serializers.AssetYamlSerializer.Load(Stream stream, String assetFileExtension, ILogger log)
   at SiliconStudio.Assets.AssetSerializer.Load(Stream stream, String assetFileExtension, ILogger log)
   at SiliconStudio.Assets.AssetSerializer.Load(String filePath, ILogger log)
   at SiliconStudio.Assets.AssetSerializer.Load[T](String filePath, ILogger log)
   at SiliconStudio.Assets.Package.LoadRaw(ILogger log, String filePath)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   at SiliconStudio.Assets.PackageStore..ctor(String installationPath, String defaultPackageName, String defaultPackageVersion)
   at SiliconStudio.Assets.PackageStore.<.cctor>b__4()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at SiliconStudio.Assets.PackageStore.get_Instance()
   at SiliconStudio.Assets.PackageSession..ctor(Package package)
   at SiliconStudio.Assets.PackageSession..ctor()
   at SiliconStudio.Paradox.GameStudio.Program.<Startup>d__d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at SiliconStudio.Paradox.GameStudio.Program.Main()

**Comment by xen2** [comment] 2015-09-13 10:23
GameStudio toolchain only runs on x64 (duplicate of #295).

Sorry for not showing a proper error message when that condition is not met, we need to fix that!

**Closed by xen2** 2015-09-13 10:23 UTC
