### ISSUE TITLE
Debug primitives

### ISSUE THREAD

**Issue by kerams** [SiliconStudio/paradox#184] opened 2015-02-15 21:14 UTC
Just updated from beta06 to beta10 and debug primitives stopped working all of a sudden. I am doing the standard

    Physics.PhysicsEngine.CreateDebugPrimitives = true;
    Physics.PhysicsEngine.RenderDebugPrimitives = true;
    Physics.PhysicsEngine.DebugEffect = new PhysicsDebugEffect(GraphicsDevice);

Do I need to initialize them differently? I did not notice any mention of debug primitives in the release notes.

**Comment by sinkingsugar** [comment] 2015-02-15 21:56
Thanks for the report.
I'm not sure but I have to investigate as I noticed the same even in our internal branches. The debug render is using pipeline.endpass. Something must have changed.

**Comment by sinkingsugar** [comment] 2015-02-17 00:21
The issue is the PhysicsDebugEffect shader itself. Physics has changed a lot in a future branch, but I will try to push a fix for this branch as soon as possible.

**Comment by sinkingsugar** [comment] 2015-02-17 19:39
All done. Should be fixed in the next release!

**Comment by kerams** [comment] 2015-02-17 19:41
Thank you.

**Closed** 2015-06-12 00:45 UTC
Labels: fixed
