### ISSUE TITLE
Script.Start not being called

### ISSUE THREAD

**Issue by nug700** [SiliconStudio/paradox#244] opened 2015-07-13 01:04 UTC
Using ScriptComponent.Scripts.Add does not call the Script.Start override function of the script during runtime. Is this the correct way to add scripts during runtime, because this way doesn't seem to be initializing the custom component correctly.

**Comment by xenux** [comment] 2015-07-13 02:10
Hi nug, I think that you are using it right. This is probably a bug on our side. We will fix that asap. Thanks for the report.

**Comment by jwollen** [comment] 2015-07-13 08:50
This seems to work correctly right now. Could you describe how to reproduce this?

Note that the ScriptComponent must be part of an Entity, and the Entity part of the current Scene (Adding Entities later will start their Scripts, too, of couse).
Also, adding Scripts is done in a deferred fashion: It happens at the beginning of the next frame.

**Comment by nug700** [comment] 2015-07-13 19:25
Yea it seems to be working for me now. The code I based this issue on is long gone, so I can't remember what I did to make it not work

**Comment by xenux** [comment] 2015-07-17 10:27
I close the issue as it seems to be fixed. Feel free to reopen it if you re-experience the problem again.

**Closed by xenux** 2015-07-17 10:27 UTC
Labels: bug, invalid
