### ISSUE TITLE
Exception in Paradox Studio when saving after saving script change in Visual Studio.

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/paradox#281] opened 2015-08-22 02:31 UTC
Hi,

Much sadness....

Setup:
* Paradox Studio 1.2.2-beta
* Visual Studio 2015 Community
* Windows 10

Steps to reproduce:

1. Create new project based on SpriteEntity sample.
2. Open solution in Visual Studio
3. Add a public property to a script (I add a `int` to `LogicScript')
4. Save script file
5. When the popup prompts you to click it to sync changes with Paradox Studio; Do so.
6. In paradox Paradox Studio make a change (i change X coordinate of the PLayer Entity) and press save.
7. KABOOM!!!!

The exception complains about the `SpriteEntity.BeamScript` but i didn't even touch it.

```
Paradox Version: 1.2.2-beta
GameStudio Version: 4
Default session graphics profile: Level_9_1
Current Directory: C:\Program Files (x86)\Paradox
Command Line Args: D:\Dev Projects\Paradox\SpriteEntity\SpriteEntity.sln /LauncherWindowHandle 132356
OS Version: Microsoft Windows NT 6.2.9200.0 (x64)
Processor Count: 8
Video configuration:
GPU 1
BitsPerPel: 32
Caption: NVIDIA GeForce GTX 580
Description: NVIDIA GeForce GTX 580
DeviceName: NVIDIA GeForce GTX 580
DisplayFlags: 0
DisplayFrequency: 60
DitherType: 
DriverVersion: 
ICMIntent: 
ICMMethod: 
LogPixels: 96
PelsHeight: 768
PelsWidth: 1024
SettingID: NVIDIA GeForce GTX 580
SpecificationVersion: 1025
Exception: ArgumentException: No serializer available for type SpriteEntity.BeamScript
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(T obj, SerializationStream stream)
   at SiliconStudio.Core.Serialization.Serializers.ListAllSerializer`2.Serialize(TList& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngineDesign_ScriptCollectionSerializer.Serialize(ScriptCollection& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(Object& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngine_ScriptComponentSerializer.Serialize(ScriptComponent& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(Object& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializerObject`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(T obj, SerializationStream stream)
   at SiliconStudio.Core.Serialization.Serializers.DictionaryAllSerializer`3.Serialize(TDictionary& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngine_EntitySerializer.Serialize(Entity& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(T obj, SerializationStream stream)
   at SiliconStudio.Core.Serialization.Serializers.KeyedSortedListSerializer`3.Serialize(TKeyedList& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxEngineDesign_EntityHierarchyDataSerializer.Serialize(EntityHierarchyData& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.Serialize(T& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxAssetsEntities_EntityAssetSerializer.Serialize(EntityAsset& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.DataSerializers.SiliconStudioParadoxAssetsEntities_SceneAssetSerializer.Serialize(SceneAsset& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.DataSerializer`1.Serialize(Object& obj, ArchiveMode mode, SerializationStream stream)
   at SiliconStudio.Core.Serialization.MemberReuseSerializer`1.SerializeExtended(T& obj, ArchiveMode mode, SerializationStream stream, DataSerializer`1 dataSerializer)
   at SiliconStudio.Core.Serialization.SerializerExtensions.SerializeExtended[T](SerializationStream stream, T obj, ArchiveMode mode, DataSerializer`1 dataSerializer)
   at SiliconStudio.Assets.AssetCloner..ctor(Object value, Boolean keepOnlySealedOverride, Boolean referencesAsNull)
   at SiliconStudio.Assets.AssetCloner.Clone(Object asset, Boolean keepOnlySealedOverride, Boolean referencesAsNull)
   at SiliconStudio.Assets.Analysis.AssetDependencyManager.Session_AssetDirtyChanged(Asset asset)
   at SiliconStudio.Assets.PackageSession.OnAssetDirtyChanged(Asset asset)
   at SiliconStudio.Assets.Package.OnAssetDirtyChanged(Asset asset)
   at SiliconStudio.Assets.AssetItem.set_IsDirty(Boolean value)
   at SiliconStudio.Assets.Editor.ViewModel.AssetViewModel.OnDirtyFlagSet(Boolean oldValue, Boolean newValue)
   at SiliconStudio.Presentation.ViewModel.DirtiableEditableViewModel.set_IsDirty(Boolean value)
   at SiliconStudio.Presentation.ViewModel.DirtiableEditableViewModel.UpdateDirtiness()
   at SiliconStudio.Presentation.ViewModel.DirtiableEditableViewModel.NotifyActionStackChange(ActionStackChange change)
   at SiliconStudio.Presentation.ViewModel.ActionStack.ViewModelActionItem.<set_IsSaved>b__0(IDirtiableViewModel x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at SiliconStudio.Presentation.ViewModel.ActionStack.ViewModelActionItem.set_IsSaved(Boolean value)
   at SiliconStudio.ActionStack.ActionStack.CreateSavePoint(Boolean markActionsAsSaved)
   at SiliconStudio.Presentation.ViewModel.ActionStack.ViewModelTransactionalActionStack.CreateSavePoint(Boolean markActionsAsSaved)
   at SiliconStudio.Presentation.ViewModel.ActionStack.ActionStackViewModel.NotifySave()
   at SiliconStudio.Assets.Editor.ViewModel.SessionViewModel.<SaveSession>d__5f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SiliconStudio.Assets.Editor.ViewModel.SessionViewModel.<<.ctor>b__3b>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at SiliconStudio.Paradox.GameStudio.Program.Main()
```

Cheers,
dfkeenan.

**Comment by xenux** [comment] 2015-08-28 00:59
Thanks for the report,

I could reproduce the bug. Will try to fix that for next release. ;-)

**Comment by jwollen** [comment] 2015-08-28 05:55
This was caused by the .pdxscene asset of the sample being slightly corrupted, and is now fixed. We will also double check the remaining samples.

**Comment by dfkeenan** [comment] 2015-08-28 06:52
Cool!

So I am if i started an empty game project it would be fine?

**Comment by jwollen** [comment] 2015-08-28 09:27
Yes, that should be fine.

**Comment by dfkeenan** [comment] 2015-08-28 09:35
Whoa! 

What was I smoking when I typed that last comment. That sentence doesn't make sense. 

I have been doing stuff like that all day.  Sometimes it's probably best just to walk away from the keyboard.

**Closed** 2015-09-18 03:40 UTC
Labels: bug, fixed
