### ISSUE TITLE
Crash ! (on a new project)

### ISSUE THREAD

**Issue by LORDMUSIC** [SiliconStudio/paradox#164] opened 2015-02-03 21:17 UTC
Paradox Version: 1.0.0-beta07
GameStudio Version: 4
Error Message: Unexpected exception
User: lordmusic
Current Directory: D:\paradox\GamePackages\Paradox.1.0.0-beta07\Bin\Windows-Direct3D11
OS Version: Microsoft Windows NT 6.2.9200.0
Command Line Args: 
Exception type: SharpDXException
Exception message: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

StackTrace:    at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at SiliconStudio.Paradox.Graphics.Texture.InitializeFromImpl(DataBox[] dataBoxes)
   at SiliconStudio.Paradox.Graphics.Texture.InitializeFrom(Texture parentTexture, TextureDescription description, TextureViewDescription viewDescription, DataBox[] textureDatas)
   at SiliconStudio.Paradox.Graphics.GraphicsPresenter.CreateDepthStencilBuffer()
   at SiliconStudio.Paradox.Graphics.GraphicsPresenter..ctor(GraphicsDevice device, PresentationParameters presentationParameters)
   at SiliconStudio.Paradox.Graphics.SwapChainGraphicsPresenter..ctor(GraphicsDevice device, PresentationParameters presentationParameters)
   at SiliconStudio.Paradox.Games.GamePlatform.CreateDevice(GraphicsDeviceInformation deviceInformation)
   at SiliconStudio.Paradox.Games.GamePlatform.ChangeOrCreateDevice(GraphicsDevice currentDevice, GraphicsDeviceInformation deviceInformation)
   at SiliconStudio.Paradox.Games.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation newInfo)
   at SiliconStudio.Paradox.Games.GraphicsDeviceManager.ChangeOrCreateDevice(Boolean forceCreate)
   at SiliconStudio.Paradox.Games.GraphicsDeviceManager.SiliconStudio.Paradox.Games.IGraphicsDeviceManager.CreateDevice()
   at SiliconStudio.Paradox.Games.GameBase.InitializeBeforeRun()
   at SiliconStudio.Paradox.Games.GamePlatform.OnInitCallback()
   at SiliconStudio.Paradox.Games.GameWindowDesktop.Run()
   at SiliconStudio.Paradox.Games.GamePlatform.Run(GameContext gameContext)
   at SiliconStudio.Paradox.Games.GameBase.Run(GameContext gameContext)
   at SiliconStudio.Paradox.GameStudio.ParadoxViewService.ParadoxUIThread(Object projectSession)
   at SiliconStudio.Core.Diagnostics.SafeAction.<>c__DisplayClass4.<Wrap>b__3(Object obj)

**Comment by xoofx** [comment] 2015-02-04 01:17
Sorry for this regression. We will have a look at it and release a fix asap.

**Comment by xen2** [comment] 2015-02-04 01:41
Thanks for the report.
What is your GPU?

Note: Duplicate of #163

**Closed** 2015-02-04 01:42 UTC
Labels: bug

**Comment by xen2** [comment] 2015-02-04 05:42
Fixed in beta08.

**Comment by LORDMUSIC** [comment] 2015-02-05 08:45
thx
